#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

# set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/setup

# boot the app and any other necessary processes.
bundle exec unicorn -c config/unicorn.rb #-E $ENV -D
