#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

# set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Installing rdoc for all gems in system"
bundle exec gem rdoc --all --ri --no-rdoc
echo "==> Everything is now ready to go!"
